---                                                                
- hosts: all                                                       
  become: yes                                                      
  gather_facts: false
                                                                   
  handlers:                                                        
    - name: nginx restart
      service: name=nginx state=restarted
      sudo: True
                                                                  
  tasks:                                                           
    - name: Install python-minimal for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: output.stdout != ""

    - name: Gathering Facts
      setup:

    - name: Update yum cache if needed                             
      yum: update_cache=yes
      when: ansible_facts['ansible_os_family'] == 'RedHat'
                                                                   
    - name: sudo add-apt-repository ppa:nginx/stable
      apt_repository:
        repo: ppa:nginx/stable
        state: present
      when: ansible_facts['ansible_os_family'] == 'Debian'

    - name: sudo apt-get update
      apt: 
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts['ansible_os_family'] == 'Debian'

    - name: sudo apt-get install nginx
      apt: name=nginx state=latest
      when: ansible_facts['ansible_os_family'] == 'Debian'

    - name: copying nginx.conf (j2)
      template:
        src: nginx.conf.j2 
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: nginx restart

    - name: force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers

    - name: ensure port is open
      wait_for:
        host: 0.0.0.0
        port: 80
        delay: 5
        state: started

    - name: "check accessibility http://tomcat_servers:{{ tomcat_server_port }}/sample/"
      uri:
        url: http://{{ ansible_host }}
      register: HTTP_code

    - debug: var=HTTP_code.status
