# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  # Application server 1.
  config.vm.define "nginx" do |app|
    app.vm.hostname = "nginx"
    app.vm.box = "ubuntu/xenial64"
    app.vm.network :private_network, ip: "192.168.60.150"
#    app.vm.provision "shell", inline: <<-SHELL
#      apt -y update
#      apt -y install python-minimal
#    SHELL
  end
  config.vm.define "centos" do |app|
    app.vm.hostname = "centos"
    app.vm.box = "centos/7"
    app.vm.network :private_network, ip: "192.168.60.160"
  end
end
