# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  # Application server 1.
  config.vm.define "nginx" do |app|
    app.vm.hostname = "loadbalancer"
    app.vm.box = "ubuntu/xenial64"
    app.vm.network :private_network, ip: "192.168.60.250"
  end
  config.vm.define "centos1" do |app|
    app.vm.hostname = "centos1"
    app.vm.box = "centos/7"
    app.vm.network :private_network, ip: "192.168.60.200"
  end
  config.vm.define "centos2" do |app|
    app.vm.hostname = "centos2"
    app.vm.box = "centos/7"
    app.vm.network :private_network, ip: "192.168.60.100"
  end
end

