# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  # Application server 1.
  config.vm.define "tomcat" do |app|
    app.vm.hostname = "tomcat.test"
    app.vm.box = "centos/7"
    app.vm.network :private_network, ip: "192.168.60.200"
  end
end
